export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'core',
        'vite-plugin',
        'webpack-plugin',
        'runtime',
        'sw',
        'resolver',
        'docs',
        'example',
        'ci',
        'deps',
        'release',
        'test',
      ],
    ],
    'scope-empty': [1, 'never'],
    'subject-max-length': [2, 'always', 100],
  },
  prompt: {
    scopes: [
      { value: 'core', name: 'core:           核心包逻辑' },
      { value: 'vite-plugin', name: 'vite-plugin:    Vite 插件' },
      { value: 'webpack-plugin', name: 'webpack-plugin: Webpack 插件' },
      { value: 'runtime', name: 'runtime:        运行时 IIFE 代码' },
      { value: 'sw', name: 'sw:             Service Worker' },
      { value: 'resolver', name: 'resolver:       解析器/路径解析' },
      { value: 'docs', name: 'docs:           文档' },
      { value: 'example', name: 'example:        示例项目' },
      { value: 'ci', name: 'ci:             CI/CD 工作流' },
      { value: 'deps', name: 'deps:           依赖更新' },
      { value: 'release', name: 'release:        发版相关' },
      { value: 'test', name: 'test:           测试' },
    ],
    enableMultipleScopes: true,
    scopeEnumSeparator: ',',
  },
};
