/**
 * Generate the small runtime bridge that Webpack executes inside its bootstrap.
 *
 * The generated code owns only Webpack's loader/callback semantics. Recovery
 * policy, circuit state, event publication, and Promise sharing stay in the
 * core coordinator exposed through the private runtime bridge.
 */
export function generateWebpackRuntimeBridge(): string {
  return [
    '/* @resource-fallback 运行时桥接 */',
    'if (typeof window !== "undefined" && window.__RF__ && window.__RF__.internal) {',
    '  try {',
    '    var __rf_internal = window.__RF__.internal;',
    '    var __rf_classify = function(event) {',
    '      if (event && (event.type === "error" || event.type === "timeout")) {',
    '        return { ok: false, failure: { kind: "load-error", error: event } };',
    '      }',
    '      return { ok: true, value: event };',
    '    };',
    '    var __rf_failure = function(reason) {',
    '      if (reason && typeof reason === "object" && reason.error !== undefined) return reason.error;',
    '      return { type: "error" };',
    '    };',
    '    var __rf_url_key = function(value) {',
    '      try {',
    '        var parsed = new URL(value, document.baseURI || location.href);',
    '        parsed.hash = "";',
    '        parsed.searchParams.delete("__rf");',
    '        return "url:" + parsed.href;',
    '      } catch (e) {',
    '        return "url:" + String(value).replace(/#.*/, "");',
    '      }',
    '    };',
    '    var __rf_load_fresh = function(url, metadata, signal) {',
    '      return new Promise(function(resolve) {',
    '        if (signal.aborted) {',
    '          resolve({ ok: false, failure: { kind: "aborted" } });',
    '          return;',
    '        }',
    '        var script = document.createElement("script");',
    '        script.charset = metadata.charset || "utf-8";',
    '        script.async = true;',
    '        if (metadata.key) script.setAttribute("data-webpack", metadata.key);',
    '        if (metadata.nonce) script.nonce = metadata.nonce;',
    '        if (metadata.crossOrigin) script.crossOrigin = metadata.crossOrigin;',
    '        if (metadata.referrerPolicy) script.referrerPolicy = metadata.referrerPolicy;',
    '        var trustedUrl = metadata.trustedScriptUrl === undefined ? url : metadata.trustedScriptUrl;',
    '        script.src = trustedUrl;',
    '        var settled = false;',
    '        var cleanup = function() {',
    '          script.onload = null;',
    '          script.onerror = null;',
    '          signal.removeEventListener("abort", onAbort);',
    '        };',
    '        var settle = function(result) {',
    '          if (settled) return;',
    '          settled = true;',
    '          cleanup();',
    '          resolve(result);',
    '        };',
    '        var onAbort = function() {',
    '          if (script.parentNode) script.parentNode.removeChild(script);',
    '          settle({ ok: false, failure: { kind: "aborted" } });',
    '        };',
    '        script.onload = function(event) { settle({ ok: true, value: event }); };',
    '        script.onerror = function() {',
    '          settle({ ok: false, failure: { kind: "load-error", error: { type: "error" } } });',
    '        };',
    '        signal.addEventListener("abort", onAbort, { once: true });',
    '        (document.head || document.body || document.documentElement).appendChild(script);',
    '      });',
    '    };',
    '    var __rf_transport = function(firstLoad, metadata) {',
    '      return {',
    '        attempt: function(input, signal) {',
    '          if (signal.aborted) return Promise.resolve({ ok: false, failure: { kind: "aborted" } });',
    '          if (input.attempt === 1) {',
    '            return new Promise(function(resolve) {',
    '              var settled = false;',
    '              var settle = function(result) {',
    '                if (settled) return;',
    '                settled = true;',
    '                resolve(result);',
    '              };',
    '              try {',
    '                firstLoad(input.url, function(event) { settle(__rf_classify(event)); });',
    '              } catch (error) {',
    '                settle({ ok: false, failure: { kind: "unknown", error: error } });',
    '              }',
    '            });',
    '          }',
    '          return __rf_load_fresh(input.url, metadata, signal);',
    '        },',
    '      };',
    '    };',
    '    var __rf_orig_l = __webpack_require__.l;',
    '    if (__rf_orig_l && !__rf_orig_l.__rf_wrapped) {',
    '      var __rf_wrapped_l = function(url, done, key, chunkId) {',
    '        var logicalKey = key',
    '          ? "chunk:" + key',
    '          : chunkId !== undefined',
    '            ? "chunk:" + String(chunkId)',
    '            : __rf_url_key(url);',
    '        var metadata = {',
    '          key: key,',
    '          chunkId: chunkId,',
    '          nonce: __webpack_require__.nc,',
    '          crossOrigin: __webpack_require__.crossOrigin,',
    '          referrerPolicy: __webpack_require__.referrerPolicy,',
    '          charset: __webpack_require__.charset,',
    '          trustedScriptUrl: __webpack_require__.trustedScriptUrl,',
    '        };',
    '        var transport = __rf_transport(function(firstUrl, complete) {',
    '          __rf_orig_l(firstUrl, complete, key, chunkId);',
    '        }, metadata);',
    '        var recovery;',
    '        try {',
    '          recovery = __rf_internal.recover({',
    '            owner: "webpack",',
    '            logicalKey: logicalKey,',
    '            initialUrl: url,',
    '            transport: transport,',
    '          });',
    '        } catch (error) {',
    '          done(error);',
    '          return;',
    '        }',
    '        recovery.then(',
    '          function(event) { done(event); },',
    '          function(reason) { done(__rf_failure(reason)); },',
    '        );',
    '      };',
    '      __rf_wrapped_l.__rf_wrapped = true;',
    '      __webpack_require__.l = __rf_wrapped_l;',
    '    }',
    '',
    '    // CSS link 元素仍由 Observer 负责替换。这里仅阻止 Webpack 的 CSS',
    '    // promise 因原始 link 失败而提前 reject，让 Observer 有机会完成替换。',
    '    var __rf_f_keys = Object.keys(__webpack_require__.f || {});',
    '    for (var __rf_i = 0; __rf_i < __rf_f_keys.length; __rf_i++) {',
    '      (function(fk) {',
    '        if (fk === "j") return;',
    '        var originalFn = __webpack_require__.f[fk];',
    '        if (typeof originalFn !== "function" || originalFn.__rf_css) return;',
    '        var wrappedFn = function(chunkId, promises) {',
    '          var before = promises.length;',
    '          originalFn(chunkId, promises);',
    '          for (var pi = before; pi < promises.length; pi++) {',
    '            promises[pi] = promises[pi].catch(function(error) {',
    '              var isCss = error && (',
    '                error.code === "CSS_CHUNK_LOAD_FAILED" ||',
    '                (error.request && /\\.css([?#]|$)/.test(error.request))',
    '              );',
    '              if (!isCss) throw error;',
    '              return undefined;',
    '            });',
    '          }',
    '        };',
    '        wrappedFn.__rf_css = true;',
    '        __webpack_require__.f[fk] = wrappedFn;',
    '      })(__rf_f_keys[__rf_i]);',
    '    }',
    '  } catch (error) { /* 降级到 Webpack 原生加载 */ }',
    '}',
  ].join('\n');
}
